name: CI Process

on:
  workflow_dispatch: # allow jobs manual run
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
gi      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn

  check-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn

      - name: cleaning codes
        run: yarn lint
